//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipCheck.Server.DataSource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingCarSSISEntities : DbContext
    {
        public BookingCarSSISEntities()
            : base("name=BookingCarSSISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<v28caxrf_s2> v28caxrf_s2 { get; set; }
        public virtual DbSet<V28EFQ7J> V28EFQ7J { get; set; }
    }
}
