//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipCheck.Server.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_III_MACHINE_EXCEPTION
    {
        public string EXCEPTION_ID { get; set; }
        public string EXCEPTION_NAME { get; set; }
        public string CREATE_TIME { get; set; }
        public string MODIFIER_ID { get; set; }
        public string MODIFY_TIME { get; set; }
        public Nullable<int> EXCEPTION_COUNT { get; set; }
        public int SERIAL_ID { get; set; }
        public string CREATOR { get; set; }
    }
}
