//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipCheck.Server.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_II_HANG_SILK_DETAIL
    {
        public string UP_SILK_NO { get; set; }
        public string RGE_FLAG_NO { get; set; }
        public string CAR_NO { get; set; }
        public string PROD_NO { get; set; }
        public string CREATOR_ID { get; set; }
        public string CREATE_TIME { get; set; }
        public string MODIFIER_ID { get; set; }
        public string MODIFY_TIME { get; set; }
        public string CHECK_NO { get; set; }
    }
}
