//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipCheck.Server.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_III_MACHINE_CHECK
    {
        public System.Guid SEQ_NO { get; set; }
        public string FAC_ID { get; set; }
        public string TWISTING_MACH_NO { get; set; }
        public string RGE_FLAG_NO { get; set; }
        public string EXCEPTION_TIME { get; set; }
        public string EXCEPTION_TYPE { get; set; }
        public string EXCEPTION_ID { get; set; }
        public string EXCEPTION_NAME { get; set; }
        public string REPAIR_TIME { get; set; }
        public string REPAIR_PERSON { get; set; }
        public string CONFIRM_TIME { get; set; }
        public string CONFIRM_PERSON { get; set; }
        public string TRANS_TIME { get; set; }
        public string TRANS_PERSON { get; set; }
    }
}
