//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipCheck.Server.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_II_PROD_TIME
    {
        public string FAC_ID { get; set; }
        public string PROD_NO { get; set; }
        public int PROD_TIME { get; set; }
    }
}
