//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipCheck.Server.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_III_PROD_SILK_LEN_TIME
    {
        public string FAC_ID { get; set; }
        public string PROD_SPEC { get; set; }
        public int SILK_LENGTH { get; set; }
        public int SILK_MINS { get; set; }
        public string CREATOR_ID { get; set; }
        public string CREATE_TIME { get; set; }
        public string MODIFIER_ID { get; set; }
        public string MODIFY_TIME { get; set; }
    }
}
