//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipCheck.Server.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserId { get; set; }
        public string Account { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public Nullable<System.DateTime> DateLastActivity { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<bool> IsActivated { get; set; }
        public string Tel { get; set; }
        public string Ext { get; set; }
        public string Contact { get; set; }
        public Nullable<bool> Category { get; set; }
    }
}
