//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipCheck.Server.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class v28caxrf_s2
    {
        public string CUFN { get; set; }
        public string ODNO { get; set; }
        public Nullable<decimal> UNPKWGT { get; set; }
        public string PDID { get; set; }
        public string CLHRLNO { get; set; }
        public Nullable<int> L { get; set; }
        public Nullable<decimal> GRSWGT { get; set; }
        public int ROWIdx { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string SHA1 { get; set; }
        public Nullable<System.DateTime> ateModified { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public string CheckAccount { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string OUTMDAT { get; set; }
    }
}
