//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipCheck.Server.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class V28EFQ7J
    {
        public string CUNO { get; set; }
        public string OMNO { get; set; }
        public string KD { get; set; }
        public string SPEC { get; set; }
        public string IKPCNO { get; set; }
        public decimal L { get; set; }
        public Nullable<int> NETWGT { get; set; }
        public int ROWIdx { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string SHA1 { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public string CheckAccount { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string IKDAT { get; set; }
    }
}
